#EX.054
#CRIE UM PROGRAMA QUE LEIA O ANO DE NASCIMENTO DE SETE PESSOAS. 
#NO FINAL, MOSTRE QUANTAS PESSOAS AINDA NÃO ATINGIRAM A MAIORIDADE E 
#QUANTAS JÁ SÃO MAIORES.
#CONSIDERE A MAIORIDADE 21 ANOS.