#ESTRUTURAS DE CONTROLES CONDIÇÕES E LAÇOS

#CONDIÇÕES SIMPLES, COMPOSTAS E ANINHADAS
#INTERAÇÕES ESTRUTURA DE REPETIÇÃO COM VARIAVEIS DE CONTROLE, COM TESTE LÓGICO NO INICIO E REPETIÇÕES INFINITAS COM INTERRUPÇÕES NO MEIO
